title: Algoritmos Genéticos
description: Aprendamos sobre algoritmos genéticos con python, emocionante ¿verdad? ;)

remote_theme: pages-themes/athena
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#url: https://biojuampa.github.io/Algoritmos_Geneticos/
